import type { SafetyReport } from "../types";

export const SEED_REPORTS: Omit<SafetyReport, "id">[] = [
  {
    userId: "seed",
    locationName: "Central Park - South Entrance",
    lat: 40.7674,
    lng: -73.9712,
    timeOfDay: "evening",
    lighting: 4,
    visibility: 4,
    crowdLevel: 5,
    accessibility: 4,
    emergencyAccess: 4,
    harassmentConcern: 5,
    overallComfort: 4,
    comment: "Well-lit and active area, feels very safe during evening hours.",
    issueTags: [],
    score: 88,
    riskLevel: "Safe",
    recommendation: "This space shows strong safety characteristics. Continue regular maintenance and community engagement to sustain safety standards.",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    userId: "seed",
    locationName: "Brooklyn Bridge Walkway",
    lat: 40.7061,
    lng: -73.9969,
    timeOfDay: "morning",
    lighting: 3,
    visibility: 4,
    crowdLevel: 3,
    accessibility: 3,
    emergencyAccess: 3,
    harassmentConcern: 4,
    overallComfort: 3,
    comment: "Moderate foot traffic in the morning. Could use better railings.",
    issueTags: ["poor_accessibility"],
    score: 62,
    riskLevel: "Moderate",
    recommendation: "Conduct an accessibility audit and implement inclusive design standards.",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    userId: "seed",
    locationName: "Lower East Side Alley - Delancey St",
    lat: 40.7183,
    lng: -73.9836,
    timeOfDay: "night",
    lighting: 1,
    visibility: 1,
    crowdLevel: 1,
    accessibility: 2,
    emergencyAccess: 1,
    harassmentConcern: 1,
    overallComfort: 1,
    comment: "Very poorly lit at night. Feels completely unsafe and isolated.",
    issueTags: ["poor_lighting", "isolated_path", "no_cctv", "no_emergency_help"],
    score: 12,
    riskLevel: "Unsafe",
    recommendation: "Install uniform street lighting and eliminate dark patches along pathways. Improve activity zones near the path, increase surveillance cameras, and create alternative well-used routes. Install CCTV cameras at key intersections and entry/exit points with visible signage. Place emergency call boxes, first-aid stations, and clearly marked emergency contact points.",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    userId: "seed",
    locationName: "Times Square - 7th Ave Plaza",
    lat: 40.758,
    lng: -73.9855,
    timeOfDay: "night",
    lighting: 5,
    visibility: 5,
    crowdLevel: 5,
    accessibility: 4,
    emergencyAccess: 4,
    harassmentConcern: 3,
    overallComfort: 4,
    comment: "Extremely bright and busy. Some harassment concerns near tourist traps.",
    issueTags: [],
    score: 82,
    riskLevel: "Safe",
    recommendation: "This space shows strong safety characteristics. Continue regular maintenance and community engagement to sustain safety standards.",
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    userId: "seed",
    locationName: "Prospect Park - West Drive",
    lat: 40.6602,
    lng: -73.9769,
    timeOfDay: "evening",
    lighting: 2,
    visibility: 2,
    crowdLevel: 2,
    accessibility: 3,
    emergencyAccess: 2,
    harassmentConcern: 2,
    overallComfort: 2,
    comment: "Dense trees block visibility. Very few people in the evening.",
    issueTags: ["poor_lighting", "obstructed_visibility", "low_footfall", "no_emergency_help"],
    score: 28,
    riskLevel: "Unsafe",
    recommendation: "Install uniform street lighting and eliminate dark patches along pathways. Trim overgrown vegetation, remove visual barriers, and redesign sightlines for open surveillance. Introduce mixed-use activities, street vendors, or events to increase pedestrian flow. Place emergency call boxes, first-aid stations, and clearly marked emergency contact points.",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    userId: "seed",
    locationName: "High Line Park - Chelsea Section",
    lat: 40.748,
    lng: -74.005,
    timeOfDay: "afternoon",
    lighting: 5,
    visibility: 5,
    crowdLevel: 4,
    accessibility: 4,
    emergencyAccess: 3,
    harassmentConcern: 5,
    overallComfort: 5,
    comment: "Great visibility and always busy during daytime. Well maintained.",
    issueTags: [],
    score: 91,
    riskLevel: "Safe",
    recommendation: "This space shows strong safety characteristics. Continue regular maintenance and community engagement to sustain safety standards.",
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    userId: "seed",
    locationName: "Queensboro Plaza Underpass",
    lat: 40.7498,
    lng: -73.9416,
    timeOfDay: "night",
    lighting: 2,
    visibility: 2,
    crowdLevel: 1,
    accessibility: 3,
    emergencyAccess: 2,
    harassmentConcern: 2,
    overallComfort: 2,
    comment: "Dark underpass with no cameras. Feels very exposed at night.",
    issueTags: ["poor_lighting", "no_cctv", "isolated_path", "hidden_seating"],
    score: 22,
    riskLevel: "Unsafe",
    recommendation: "Install uniform street lighting and eliminate dark patches along pathways. Install CCTV cameras at key intersections and entry/exit points with visible signage. Improve activity zones near the path.",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    userId: "seed",
    locationName: "Union Square - North Plaza",
    lat: 40.7359,
    lng: -73.9911,
    timeOfDay: "afternoon",
    lighting: 4,
    visibility: 4,
    crowdLevel: 5,
    accessibility: 4,
    emergencyAccess: 4,
    harassmentConcern: 4,
    overallComfort: 4,
    comment: "Very active market area. Good safety presence.",
    issueTags: [],
    score: 80,
    riskLevel: "Safe",
    recommendation: "This space shows strong safety characteristics. Continue regular maintenance and community engagement to sustain safety standards.",
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
